formatter: markdown table

header-from: ./.docs/header.md #optional
footer-from: ./.docs/footer.md #optional 

sections:
  show:
    - header
    - requirements    
    - providers
    - modules
    - inputs    
    - outputs
    - footer

sort:
  enabled: true
  by: required

settings:
  anchor: true
  indent: 4
  escape: false
  default: true
  required: true
  type: true
  hide-empty: true