name: Generate terraform docs # Nome do workflow

on:
  push: # Evento que aciona o workflow
    paths:
      - 'module/**' # Caminho do código fonte que aciona o workflow
    branches:
      - main # Branch que aciona o workflow
  pull_request: # Evento que aciona o workflow
    paths:
      - 'module/**' # Caminho do código fonte que aciona o workflow
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  
  python:
    runs-on: ubuntu-latest # Define o sistema operacional do runner
    permissions:
      contents: write # Permissão para escrever no conteúdo do repositório
      pull-requests: write # Permissão para escrever em pull requests
    steps:
      - uses: actions/checkout@v3 # Ação para fazer checkout do código fonte
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Refere-se ao branch da pull request

      - name: Set up Python # Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Define a versão do Python

      - name: Install terraform-docs # Instala o terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz # Baixa o arquivo compactado
          mkdir terraform-docs # Cria um diretório
          tar -xzf terraform-docs.tar.gz terraform-docs # Descompacta o arquivo baixado
          chmod +x terraform-docs/terraform-docs # Torna o arquivo executável
          mv terraform-docs/terraform-docs /usr/local/bin/terraform-docs # Move o arquivo para o diretório binário
          rm terraform-docs.tar.gz # Remove o arquivo compactado
          rm -rf terraform-docs # Remove o diretório

      - name: Run docs.py # Executa o script docs.py
        run: python docs.py

      - name: Commit and Push changes # Comita e envia as mudanças
        run: |
          git config --global user.email "marcelobuzzetti@gmail.com" # Configura o email do usuário
          git config --global user.name "Marcelo Buzzetti" # Configura o nome do usuário
          git add . # Adiciona todas as mudanças
          git commit -m "Update README.md" # Comita as mudanças com uma mensagem
          git push # Envia as mudanças para o repositório remoto