# Nome do workflow
name: Generate terraform docs

# Evento que aciona o workflow
on:
  push:
    # Caminho do código fonte que aciona o workflow
    paths:
      - 'module/**'
    # Branch que aciona o workflow
    branches:
      - main
  pull_request:
    # Caminho do código fonte que aciona o workflow
    paths:
      - 'module/**'
  # Permite que o workflow seja acionado manualmente
  workflow_dispatch:

jobs:
  python:
    # Define o sistema operacional do runner
    runs-on: ubuntu-latest
    permissions:
      # Permissão para escrever no conteúdo do repositório
      contents: write
      # Permissão para escrever em pull requests
      pull-requests: write
    steps:
      # Ação para fazer checkout do código fonte
      - uses: actions/checkout@v3
        with:
          # Refere-se ao branch da pull request
          ref: ${{ github.event.pull_request.head.ref }}

      # Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # Define a versão do Python
          python-version: '3.12'

      # Instala o terraform-docs
      - name: Install terraform-docs
        run: |
          # Baixa o arquivo compactado
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz
          # Cria um diretório
          mkdir terraform-docs
          # Descompacta o arquivo baixado
          tar -xzf terraform-docs.tar.gz -C terraform-docs
          # Torna o arquivo executável
          chmod +x terraform-docs/terraform-docs
          # Move o arquivo para o diretório binário
          mv terraform-docs/terraform-docs /usr/local/bin/terraform-docs
          # Remove o arquivo compactado
          rm terraform-docs.tar.gz
          # Remove o diretório
          rm -rf terraform-docs

      # Executa o script docs.py
      - name: Run docs.py
        run: python docs.py

      # Comita e envia as mudanças
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}